[tool.poetry]
name = "klick_brick_cli"
version = "0.1.6"
description = ""
authors = ["David Knepprath <david.knepprath@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
behave = "^1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
